name: check-available-pytorch-dists

on:
  pull_request:
    paths:
      - .github/issue-templates/packages-out-of-sync.md
      - .github/workflows/check-available-pytorch-dists.yml
      - scripts/check_pytorch_package_indices.py

  schedule:
    - cron: "0 4 * * *"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup development environment
        uses: ./.github/actions/setup-dev-env

      - name: Check available packages on PyTorch indices
        id: packages
        run: |
          OUT=$(python scripts/check_pytorch_package_indices.py)
          echo $OUT | jq

          MISSING=$(echo $OUT | jq -r '.missing | join(",")')
          echo "missing=${MISSING}" >> $GITHUB_OUTPUT

          EXTRA=$(echo $OUT | jq -r '.extra | join(",")')
          echo "extra=${EXTRA}" >> $GITHUB_OUTPUT

          [ -z "${MISSING}${EXTRA}" ];

      - if: failure()
        name: Publish information from template
        uses: .github/actions/publish-from-template
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MISSING: ${{ steps.packages.outputs.missing }}
          EXTRA: ${{ steps.packages.outputs.extra }}
        with:
          filename: .github/issue-templates/packages-out-of-sync.md
